### ISSUE TITLE
Clicking through games randomly will sometimes open the game, doesn't happen without skin.

### ISSUE THREAD

**Issue by BlueNova0119OnDiscord** [uwuAngelo/LIGHT-UI#10]
https://user-images.githubusercontent.com/51885365/132418606-4abe82a0-f553-4918-8d6e-cd7f52c2c035.mp4

**Comment by uwuAngelo** [comment]
Maybe you're double clicking?

**Comment by BlueNova0119OnDiscord** [comment]
I think I'd know if I was double clicking. It happens often and only while using this skin.

**Comment by uwuAngelo** [comment]
it doesn't happen for me tho
