### ISSUE TITLE
Steam Overlay Issues

### ISSUE THREAD

**Issue by mohcow** [uwuAngelo/LIGHT-UI#4]
Following Issues i've encountered with Steam Overlay using Dark UI:

- Buttons are too short and therefore text gets cut off -> https://i.imgur.com/hhljn1N.png
- Web Browser is missing a proper close icon (button is top right but it's invisible) and forward button is misaligned -> https://i.imgur.com/CgQ4tjO.png
- Web Browser's Dark mode is making Websites look weird(dunno if this is my Win10 Theme tho) -> https://i.imgur.com/WXglI1h.png
- Settings close button is misaligned -> https://i.imgur.com/OSQeSMp.png

**Comment by uwuAngelo** [comment]
settings close button should be aligned now
