### ISSUE TITLE
Why is there a bug on my homepage?

### ISSUE THREAD

**Issue by HuaJiYa520** [uwuAngelo/LIGHT-UI#5]
![Snipaste_2021-08-29_00-27-58](https://user-images.githubusercontent.com/24222132/131224549-c5acf393-9b97-4578-8304-24d659080059.png)

**Comment by uwuAngelo** [comment]
fixed

**Comment by HuaJiYa520** [comment]
Thanks for your working! And I found some bugs again:
The avatar effects in the friends list are not correct.
The button in the top right corner is not displayed correctly.
![Snipaste_2021-08-29_18-13-54](https://user-images.githubusercontent.com/24222132/131247024-ec463da2-2bba-42bd-a578-045bd72fe51a.png)
![Snipaste_2021-08-29_18-14-28](https://user-images.githubusercontent.com/24222132/131247028-a94dc0e3-8cfc-4bcc-9b1d-79fce9e88c7c.png)

**Comment by uwuAngelo** [comment]
1. I fixed the buttons on the top right not being displayed
2. disable avatar effects on settings
