### ISSUE TITLE
Text overlay bug

### ISSUE THREAD

**Issue by V3ER4AX** [uwuAngelo/LIGHT-UI#6]
Text overlay, as regards the Italian language.
Thanks for your hard work, this skin is too beautiful!
![Image](https://user-images.githubusercontent.com/89614171/131243663-a0516818-f5bb-4788-a17c-2623294c02d3.png)

**Comment by uwuAngelo** [comment]
fixed

**Comment by uwuAngelo** [comment]
thanks :)

**Comment by uwuAngelo** [comment]
thanks :)
