### ISSUE TITLE
Bugs    ：)   Display error

### ISSUE THREAD

**Issue by Beatlessity** [uwuAngelo/LIGHT-UI#7]
Thank you very much for your work. I like this skin very much. I found some problems here.

Why is my chat interface still the original skin? Does it not cover the chat interface? Do follow the steps you wrote step by step.

![%FL)PVBZI_~4GJWB}X_I01Y](https://user-images.githubusercontent.com/89698583/131525160-c9b9d7b6-2447-4a5c-bb30-cca13edf5503.png)

And when the mouse hovers over some signs, the prompt message will not be displayed, like this

![InkedAH@)JXA2 Y4UIO)SM@@Y~~K_LI](https://user-images.githubusercontent.com/89698583/131525198-8bd2efd0-8ba1-40e6-9798-485e9bf6c0dd.jpg)
![Inked582 TT`SF S%(1U~ O}8EWY_LI](https://user-images.githubusercontent.com/89698583/131525210-607baece-7b0a-4791-a099-9606deadbffa.jpg)

Note that where the arrow indicates is where the mouse hovers.

Is the label here intentional ? :)

![InkedH}$FU@W%%76_NSY 2GO_4@S_LI](https://user-images.githubusercontent.com/89698583/131527062-a819a911-158f-461c-bbf5-657ab790837c.jpg)

**Comment by uwuAngelo** [comment]
The chat interface not being skined is steam's fault, open the steamfriendspatcher app and keep clicking the force check button until it skins the interface properly.I will fix the store interface bugs later. :)

**Comment by Beatlessity** [comment]
okay, thank you.

By the way, the skin has normally adapted to the chat interface.

Thank you again for your work.

**Comment by uwuAngelo** [comment]
fixed

**Comment by uwuAngelo** [comment]
is the launch options window fixed?

**Comment by Beatlessity** [comment]
it becomes............an another display error.
![image](https://user-images.githubusercontent.com/89698583/131679345-4cf74872-8287-4cba-ad22-19064b7c76b5.png)

And the store interface has been repaired.
![image](https://user-images.githubusercontent.com/89698583/131680990-d3bb062f-97b1-431e-8ae3-3f9620c320a4.png)

but my chat interface went wrong again.The following is the error report of steamfriendsPatcher.
![image](https://user-images.githubusercontent.com/89698583/131681387-8fa18c30-ccaa-4e8f-bdc7-3c8e8129ac20.png)
![image](https://user-images.githubusercontent.com/89698583/131681434-262b77a6-76e2-4b79-9bc9-17788c794c88.png)
it black again...............

**Comment by uwuAngelo** [comment]
-repeat previous steps maybe?
-is the  launch window fixed?

**Comment by Beatlessity** [comment]
No,it becomes this.The two labels are always unequal in length.
![image](https://user-images.githubusercontent.com/89698583/131795988-5302ffa2-58fe-490d-bce3-c6120d2ba97b.png)

Here, as long as the mouse is not suspended, it can't be displayed. Is it deliberately made like this？  :)
![image](https://user-images.githubusercontent.com/89698583/131797276-eeafde74-4fbc-4a9e-83b7-e18a4bdcfaa0.png)
![image](https://user-images.githubusercontent.com/89698583/131796733-d6ef990f-073c-449d-b501-427f16b161d5.png)
There are similar places。
![image](https://user-images.githubusercontent.com/89698583/131797551-aee9bfd0-be93-44d4-a8f3-9a92774efae6.png)


As for the chat interface, it's not important anymore. I dont use it often anyway.I think this should be my computer problem, so it's just an individual case.

**Comment by Beatlessity** [comment]
![image](https://user-images.githubusercontent.com/89698583/131837912-b14e2aa3-c347-4ed4-af60-70c8641d2233.png)
![image](https://user-images.githubusercontent.com/89698583/131838010-55b68965-30f5-48ed-b2d2-0dd62b2e8068.png)
They were completely repaired！  :)
I haven't found any problems yet. If I find problems again, I will give feedback in time.
Thank you for your hard work again .

**Comment by uwuAngelo** [comment]
Thanks :)
